### PR TITLE
Encrypt 2

### PR DESCRIPTION
**Pull request by RheshaVinod**
Handaling sentences for encryption

Description:
added commands to modify the key according to the spaces in the sentence

Closes issue #2

### CODE REVIEW

**Comment by shriyays** [comment]
Hey I don't see where you've made changes for handling sentences as input for encryption?

**Comment by shriyays** [comment]
> Its in the encrypt.c file

Hey. I can only see they new key generation and the encryption code but not the input for sentences. please check again :)

**Comment by RheshaVinod** [comment]
Hey, This pull request has still not been reviewed. Could u look into it

**Comment by shriyays** [comment]
> Hey, This pull request has still not been reviewed. Could u look into it

Hey. I'm so sorry for the delay. I will look into it ASAP.

**Comment by shriyays** [comment]
> Hey, This pull request has still not been reviewed. Could u look into it

Hey, I've been running into some issue while executing your code Im not sure if there's an error in the  code or something that my system wont comprehend. if you could post a screenshot of the output, it'd be of great help.

**Comment by RheshaVinod** [comment]
> > Hey, This pull request has still not been reviewed. Could u look into it
> 
> Hey, I've been running into some issue while executing your code Im not sure if there's an error in the code or something that my system wont comprehend. if you could post a screenshot of the output, it'd be of great help.

image

**Comment by shriyays** [comment]
great work there. sorry for the trouble.

**Comment by shriyays** [comment]
!bounty 50

**Pull request closed without merging**
