### PR TITLE
Closes #2

### LINKED ISSUE #2: Bug- handle sentence input
# Handle a sentence input from user
## Description
To accept sentence input from the user for encryption
## Resources
https://www.geeksforgeeks.org/vigenere-cipher/
<hr>
** Bounty points alloted : 50 **
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

### PR DESCRIPTION
**Pull request by Obsarian**
Changes:
-Replaced the scanf() function in main with fgets() to handle the sentence input in encrypt.

Closes #2

### CODE REVIEW

**Comment by Obsarian** [comment]
Hey, can you please check this? It wasn't 'assigned' to me but they still said it would be valid.

**Comment by Obsarian** [comment]
Can you please review this pull request?

**Comment by shriyays** [comment]
> Can you please review this pull request?


Hey. I'm so sorry for the delay. I will look into it ASAP.

**Comment by Obsarian** [comment]
Hey, can you please look into my code? it looks like the code after mine has been checked, so just a friendly reminder.

**Comment by Obsarian** [comment]
> > Can you please review this pull request?
> 
> Hey. I'm so sorry for the delay. I will look into it ASAP.

Hi there, sorry to pester you. I PR'ed my branch 3 hours back, i've been waiting for an update. Thank you for looking into this.

**Comment by shriyays** [comment]
> Hey, can you please check this? It wasn't 'assigned' to me but they still said it would be valid.

Yes. i will look into it right away and get back to you. Don't worry :)

**Comment by shriyays** [comment]
hey there @Obsarian , I've found some errors in your code. please look into it and make the required changes :)

**Comment by Obsarian** [comment]
> hey there @Obsarian , I've found some errors in your code. please look into it and make the required changes :)

What exactly was the error?
I ran the code and it was working for me.

**Comment by shriyays** [comment]
> > hey there @Obsarian , I've found some errors in your code. please look into it and make the required changes :)
> 
> What exactly was the error? I ran the code and it was working for me.

the error is in file_encryption. please check again and let me know . if you're still getting the right output drop a screenshot of it and our team will get back to you. :) sorry for the hassle.

**Pull request closed without merging**
