### PR TITLE
Closes #2 & #3

### LINKED ISSUE #2: Bug- handle sentence input
# Handle a sentence input from user
## Description
To accept sentence input from the user for encryption
## Resources
https://www.geeksforgeeks.org/vigenere-cipher/
<hr>
** Bounty points alloted : 50 **
Any further improvements along with bug fixes will be given brownie points. If the
countributor
sees any further inprovements that can be done to this project ,raise an issue.

### PR DESCRIPTION
**Pull request by Obsarian**
Changes:
-Added the sentence input to encrypt and decrypt functions by using fgets().

Closes #2 , #3

### CODE REVIEW

**Comment by Obsarian** [comment]
Hey, please do check this, I have edited it and it is working. Thank you.

**Comment by shriyays** [comment]
Hey @Obsarian we're so sorry for the trouble but we're running into some issues with the C files. Please drop a screenshot of the required issues and we'll look into it.

**Comment by Obsarian** [comment]
Hi, I would like to know where i should share the screenshots of my code. THank you.

**Comment by shriyays** [comment]
> Hi, I would like to know where i should share the screenshots of my code. THank you.
the comment section right here will do.

**Comment by Obsarian** [comment]
file_decrypt.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "header.h"

void file_decryption(char key[])
{
    //open the cipher text file
    FILE *f1 = fopen("cipher.txt", "r");

    //codition to check for error in opening the file
    if (f1 == NULL)
        printf("error in opening the file");

    else
    {
        char ch;
        int keyLen = strlen(key), i, j;

        //to find the length of the message in the file
        int ciphertext_len = 0;
        for (int i = 0; (ch = fgetc(f1)) != EOF; i++)
        {
            if (((ch >= 'A') && (ch <= 'Z')) || ch == 32)
                ciphertext_len++;
        }
        //printf("cipher text length: %d\n", ciphertext_len);

        char *newKey = (char*)malloc((ciphertext_len+1)*sizeof(char));
        char *decryptedMessage = (char*)malloc((ciphertext_len+1)*sizeof(char));

        //generating new key
        for (i = 0, j = 0; i < ciphertext_len; ++i, ++j)
        {
            if (j == keyLen)
                j = 0;

            newKey[i] = key[j];
        }
        newKey[i] = '\0';
        printf("\nNew Generated Key: %s\n", newKey);

        rewind(f1);
        FILE *f2 = fopen("filedecrypt.txt", "w");
        ch = '0';
        for(i = 0; i < ciphertext_len && (ch = fgetc(f1)) != EOF; i++)
        {
            if(ch != 32) {decryptedMessage[i] = (((ch - newKey[i]) + 26) % 26) + 'A';}
            else {decryptedMessage[i] = ch;}
            fputc(decryptedMessage[i], f2);
        }
        decryptedMessage[i] = '\0';
        printf("\nActual Message: %s", decryptedMessage);
        fclose(f2);
        
    }
    fclose(f1);
}

**Comment by Obsarian** [comment]
file_encrypt.c

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "header.h"

void file_encryption(char key[])
{
    FILE *f1 = fopen("plaintext.txt", "r");

    if (f1 == NULL)
        printf("error in opening the file");

    else
    {
        char ch;
        int keyLen = strlen(key), i, j;

        int ciphertext_len = 0;
        for (int i = 0; (ch = fgetc(f1)) != EOF; i++)
        {
            if (((ch >= 'A') && (ch <= 'Z')) || ch == 32)
                ciphertext_len++;
        }
        //printf("cipher text length: %d\n", ciphertext_len);

        char *newKey = (char*)malloc((ciphertext_len+1)*sizeof(char));
        char *encryptedMessage = (char*)malloc((ciphertext_len+1)*sizeof(char));

        //generating new key
        for (i = 0, j = 0; i < ciphertext_len; ++i, ++j)
        {
            if (j == keyLen)
                j = 0;

            newKey[i] = key[j];
        }
        newKey[i] = '\0';
        printf("\nNew Generated Key: %s\n", newKey);

        rewind(f1);
        FILE *f2 = fopen("fileencrypt.txt", "w");
        ch = '0';
        for(i = 0; i < ciphertext_len && (ch = fgetc(f1)) != EOF; i++)
        {
            if(ch != 32) {encryptedMessage[i] = ((ch + newKey[i]) % 26) + 'A';}
            else {encryptedMessage[i] = ch;}
            fputc(encryptedMessage[i], f2);
        }
        encryptedMessage[i] = '\0';
        printf("\nEncrypted Message: %s", encryptedMessage);
        fclose(f2);
    }
    fclose(f1);
}

**Comment by Obsarian** [comment]
I have shared the code here. Kindly review it. Thank you.

**Comment by shriyays** [comment]
> I have shared the code here. Kindly review it. Thank you.

hey I'm sorry for the confusion. but we need screenshots of the output.

**Comment by Obsarian** [comment]
image
image
image
image

**Comment by Obsarian** [comment]
Here are the screenshots. Please do review. thank you.

**Comment by shriyays** [comment]
Great work there!

**Comment by shriyays** [comment]
!bounty 110

**Comment by Obsarian** [comment]
Thanks a lot!

**Pull request closed without merging**
