### PR TITLE
Decrypt 3

### LINKED ISSUE #3: Bug- handle sentence input #2
# handle sentence input
To handle sentence input from the user for decryption.
# Resources
https://www.geeksforgeeks.org/vigenere-cipher/
 <hr>
** Bounty points alloted : 50 ** 
Any further improvements along with bug fixes will be given brownie points. If the countributor sees any further inprovements that can be done to this project ,raise an issue.

### PR DESCRIPTION
**Pull request by RheshaVinod**
Decryption for sentences

Description:
Added commands to generate key according to the spaces in the cipher text

Closes #3

### CODE REVIEW

**Comment by RheshaVinod** [comment]
Hey, This pull request has not been reviewed yet.Could u look into it

**Comment by shriyays** [comment]
> Hey, This pull request has not been reviewed yet.Could u look into it


Hey. I'm so sorry for the delay. I will look into it ASAP.

**Comment by shriyays** [comment]
Perfect!

**Comment by shriyays** [comment]
!bounty 50

**Pull request closed without merging**
